DROP TABLE IF EXISTS CUSTOM_TMP_TEST_USER;

CREATE TABLE CUSTOM_TMP_TEST_USER (
  ID                   VARCHAR(36) NOT NULL COMMENT '主键ID',
  USERNAME             VARCHAR(64) NOT NULL COMMENT '用户名',
  FULL_NAME            VARCHAR(36) NOT NULL COMMENT '姓名',
  MOBILE_PHONE         VARCHAR(36) NOT NULL COMMENT '移动电话',
  ID_CARD              VARCHAR(36) DEFAULT NULL COMMENT '身份证',
  EMAIL                VARCHAR(36) DEFAULT NULL COMMENT '电子邮箱',
  BIRTHDAY             DATE DEFAULT NULL COMMENT '出生日期',
  CREATED_BY           VARCHAR(36) COMMENT '创建人',
  CREATED_TIME         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  LAST_UPDATED_BY      VARCHAR(36) COMMENT '最后修改人',
  LAST_UPDATED_TIME    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  DELETE_FLAG          TINYINT NOT NULL DEFAULT 1 COMMENT '删除标记，0：已删除；1：未删除',
  PRIMARY KEY (ID)
) COMMENT '自定义模板测试用户';

INSERT INTO CUSTOM_TMP_TEST_USER (ID, USERNAME, FULL_NAME, MOBILE_PHONE, ID_CARD, EMAIL, BIRTHDAY, DELETE_FLAG) VALUES
    ('1', 'test1', '测试1', '18866668888', '1234567891', 'test1@168.com', '2022-12-12', 1),
    ('2', 'test2', '测试2', '18688886666', '1234567892', 'test2@168.com', '2022-12-12', 1);
