package cn.tablego.project.springboot.model;

import javax.validation.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonProperty;

import cn.tablego.project.springboot.common.model.BaseBean;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

/**
 * 部门(t_department)
 *
 * @author bianj
 * @version 1.0.0 2022-08-18
 */
@Setter
@Getter
@Accessors(chain = true)
public class Department extends BaseBean {
    /** 版本号 */
    private static final long serialVersionUID = -8560053048129057006L;

    /** 创建部门实例对象 */
    public static Department newInstance() {
        return new Department();
    }

    /* This code was generated by TableGo tools, mark 1 begin. */

    @ApiModelProperty(value = "主键ID", position = 1)
    @JsonProperty(index = 1)
    private String id;

    @ApiModelProperty(value = "父ID", position = 2)
    @JsonProperty(index = 2)
    @NotBlank(message = "父ID不能为空！")
    private String parentId;

    @ApiModelProperty(value = "部门名称", position = 3)
    @JsonProperty(index = 3)
    @NotBlank(message = "部门名称不能为空！")
    private String deptName;

    @ApiModelProperty(value = "部门编码", position = 4)
    @JsonProperty(index = 4)
    @NotBlank(message = "部门编码不能为空！")
    private String deptCode;

    @ApiModelProperty(value = "排序", position = 5)
    @JsonProperty(index = 5)
    private Integer sortNo;

    @ApiModelProperty(value = "租户编码", position = 6)
    @JsonProperty(index = 6)
    private String tenantCode;

    /* This code was generated by TableGo tools, mark 1 end. */
}