package cn.tablego.project.springboot.model;

import javax.validation.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonProperty;

import cn.tablego.project.springboot.common.model.BaseBean;
import io.swagger.annotations.ApiModelProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

/**
 * 系统参数(t_sys_param)
 *
 * @author bianj
 * @version 1.0.0 2021-07-18
 */
@Setter
@Getter
@Accessors(chain = true)
public class SysParam extends BaseBean {
    /** 版本号 */
    private static final long serialVersionUID = 3474695453747198483L;

    /** 创建系统参数实例对象 */
    public static SysParam newInstance() {
        return new SysParam();
    }

    /* This code was generated by TableGo tools, mark 1 begin. */

    @ApiModelProperty(value = "主键ID", position = 1)
    @JsonProperty(index = 1)
    private String id;

    @ApiModelProperty(value = "参数名称", position = 2)
    @JsonProperty(index = 2)
    @NotBlank(message = "参数名称不能为空！")
    private String paramName;

    @ApiModelProperty(value = "参数编码", position = 3)
    @JsonProperty(index = 3)
    @NotBlank(message = "参数编码不能为空！")
    private String paramCode;

    @ApiModelProperty(value = "参数类型", position = 4)
    @JsonProperty(index = 4)
    @NotBlank(message = "参数类型不能为空！")
    private String paramType;

    @ApiModelProperty(value = "参数值1", position = 5)
    @JsonProperty(index = 5)
    private String paramValue1;

    @ApiModelProperty(value = "参数值2", position = 6)
    @JsonProperty(index = 6)
    private String paramValue2;

    @ApiModelProperty(value = "参数值3", position = 7)
    @JsonProperty(index = 7)
    private String paramValue3;

    @ApiModelProperty(value = "备注", position = 8)
    @JsonProperty(index = 8)
    private String remark;

    @ApiModelProperty(value = "租户编码", position = 9)
    @JsonProperty(index = 9)
    private String tenantCode;

    /* This code was generated by TableGo tools, mark 1 end. */
}